### ISSUE TITLE
[ FEATURE ] - Display contributors on Web 💎

### ISSUE THREAD

**Issue by sachin-duhan26** [learn-opensource/learn-opensource.github.io#9]
Contributors 🌎  are most important for any open source project, hence in order to acknowledge your participation in open-source, we are looking forward to updating 💯  the [index.html](https://github.com/learn-opensource/learn-opensource.github.io/blob/master/index.html) and add dynamic content using [Github API](https://api.github.com/orgs/learn-opensource), that fetch top contributors.🤺 

## TASK OVERVIEW 🖥️ 
1. [ ] Update the [index page](https://github.com/learn-opensource/learn-opensource.github.io/blob/master/index.html).
2. [ ] Update main.js 🕺🏻  that with a call to GitHub API to fetch a list of contributors at [learn-opensource](https://github.com/learn-opensource).
3. [ ] Display the response received on [index.html](https://github.com/learn-opensource/learn-opensource.github.io/blob/master/index.html).

## UI HINTS & DETAILS
- Sort Contributors based upon the number of contributions being made. Limit the number to 20.
- Marquee tag is recommended, (although not mandatory).
- display contributors sections above the "Our Projects" section on [website](https://learn-opensource.github.io/).
- Responsiveness is a MUST.
- A preloader & paginations is optional.

## API URLs
1. [Get All Repo](https://api.github.com/orgs/learn-opensource/repos)
2. [Get All contributors for a repo](https://api.github.com/repos/learn-opensource/learn-opensource.github.io/contributors)

**Solution Hint** - Flow for this issue is nearly the same as that for fetching projects in [main.js](https://github.com/learn-opensource/learn-opensource.github.io/blob/master/js/main.js) File.

**#hacktoberfest2020 👨🏻‍💻    #hacktoberfest ❤️**

**Comment by vansh1999** [comment]
@sachin-duhan26 like to work on this

**Comment by bensbits91** [comment]
Hi @sachin-duhan26, Can I still work on this? Thanks

**Comment by vansh1999** [comment]
@bensbits91 what's the update?

**Comment by vansh1999** [comment]
let me know if you're working

**Comment by bensbits91** [comment]
@vansh1999 I'm almost done. I have the contributors displaying as cards, similar to the project cards. I have the sum of contributions for each contributor, and my final task is to sort them by total contributions. I should be done with that soon, then I'll create a PR. 

Quick screenshot:

![image](https://user-images.githubusercontent.com/56796209/96611738-d6f7af80-12b1-11eb-82a5-a0ec638983eb.png)

Feedback welcome. If you don't like the display, I'd be happy to change the format of the contributors. 

Thanks,
Ben

**Comment by bensbits91** [comment]
@sachin-duhan26 [I submitted a PR](https://github.com/learn-opensource/learn-opensource.github.io/pull/12). Feedback welcome. I'm happy to make changes if isn't what you had in mind. Thanks! Ben

**Comment by sachin-duhan26** [comment]
Hello, @bensbits91 
we might need to debug the code. 

*Reason*
![image](https://user-images.githubusercontent.com/38427564/96635212-32b94b80-1339-11eb-9987-87f9cf31c7fb.png)

[revert link](https://github.com/learn-opensource/learn-opensource.github.io/pull/13)

**Comment by bensbits91** [comment]
@sachin-duhan26 Sorry! I had it working locally. Any idea what could be different after merge?

**Comment by sachin-duhan26** [comment]
hello @bensbits91 , there can be multiple reasons, kindly check the review or the PR
one major reason I found was, that the get function in main.js got updated due to another pull request #14 resulting in conflict.

**Comment by bensbits91** [comment]
Thank you! I'll take a look as soon as possible

**Comment by bensbits91** [comment]
@sachin-duhan26 I [submitted a new PR](https://github.com/learn-opensource/learn-opensource.github.io/pull/15). Everything works locally. I don't see any conflicts
